language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install pipenv --upgrade"
  - "pipenv install --dev --skip-lock"
  - "pip install -U -e ."

script:
  - "pipenv run pytest tests --junitxml=report.xml"
  - "pipenv run flake8"
