language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install pipenv --upgrade"
  - "pipenv install --dev --skip-lock"

script:
  - "pipenv run pytest -n 8 --boxed --hypothesis-profile=exhaustive"

jobs:
  include:
    - stage: linter
      python: 3.6
      script:
        - "pipenv run flake8"
    - stage: coverage
      python: 3.6
      script:
        - "pipenv run pytest --cov=granula --hypothesis-profile=coverage"
        - "pipenv run codecov"
